### PR TITLE
JSON Web Token authentication

### PR DESCRIPTION
**Pull request by mongkok**
First, thanks for the howto-graphql, it's great  :)

Recently I develop a project to authenticate using JSON Web Token.
https://github.com/flavors/django-graphql-jwt

It is an un-official library but I think it is a good implementation for this scenario.

Some features

- [Authentication backend](https://docs.djangoproject.com/en/2.0/topics/auth/customizing/#authentication-backends) wich works perfectly together with other backends.
- Mutations to obtain token, verify and refresh it.
- It's not necessary to create a custom user model for the howto.
- Neither is it necessary to create a mutation for login.

and this is it.

### CODE REVIEW

**Comment by jonatasbaldin** [comment]
Hey mate! Thanks so much for that, it's really better than sessions :)

I'll test and take a look at the weekend, but would be really great to merge it!

**Comment by mongkok** [comment]
ok!, let me know if you need anything.

**Comment by jonatasbaldin** [comment]
Hey @mongkok, sorry for the long delay. I just started a digital nomad life and it took some time do adjust hahah I tested the implementation and it looks great, that's an awesome work!

I'm already rewriting the tutorial to fit the usage of django-graphql-jwt!

If I got into any issue using it, I'll let you know.

Thanks 🎉

**Comment by mongkok** [comment]
👍

**Comment by jonatasbaldin** [comment]
Just finish writing the changes, the [PR](https://github.com/howtographql/howtographql/pull/527) is open. Once merged, I'll merge this one as well.

Thanks mate 🎉

**Comment by mongkok** [comment]
Thanks @jonatasbaldin :)

**Comment by jonatasbaldin** [comment]
Well, it's there, merging this one!

**Comment by mongkok** [comment]
🚀

**Pull request merged**
